In [195]:
import numpy as np
import time
import os

In [196]:
current_path = os.getcwd()
filename = os.path.join(current_path, "matrix_100x100.csv")
matrix1 = np.genfromtxt(filename, delimiter=',').astype(np.float32)
print(np.shape(matrix1),np.array_equal(matrix1, matrix1.T))

filename = os.path.join(current_path, "matrix_200x200.csv")
matrix2 = np.genfromtxt(filename, delimiter=',').astype(np.float32)
print(np.shape(matrix2),np.array_equal(matrix2, matrix2.T))

filename = os.path.join(current_path, "matrix_400x400.csv")
matrix4 = np.genfromtxt(filename, delimiter=',').astype(np.float32)
print(np.shape(matrix4),np.array_equal(matrix4, matrix4.T))

filename = os.path.join(current_path, "matrix_800x800.csv")
matrix8 = np.genfromtxt(filename, delimiter=',',).astype(np.float32)
print(np.shape(matrix8),np.array_equal(matrix8, matrix8.T))

(100, 100) True
(200, 200) True
(400, 400) True
(800, 800) True


In [197]:
EPSILON = 1e-8  # Using exponentiation
MAX_ITERATIONS = 1000

In [198]:
def norm(v):
    return np.sqrt(np.dot(v,v))

def normalize(v):
    return v/norm(v)

In [199]:
def qr_householder(A):
    m, n = A.shape
    R = A.astype(float)  # Avoid unnecessary copy, ensure mutability
    Q = np.eye(m)

    for i in range(n - 1):
        # Compute the Householder vector
        u = R[i:, i].copy()  # Work with a slice; make a copy to modify
        alpha = norm(u)
        u[0] -= alpha  # Create the Householder vector in place
        norm_u = norm(u)

        if norm_u != 0:  # Avoid division by zero
            u /= norm_u

            # Apply the reflection to R in place
            R[i:, i:] -= 2 * np.outer(u, u @ R[i:, i:])
            
            # Apply the reflection to Q in place
            Q[:, i:] -= 2 * np.outer(Q[:, i:] @ u, u)
    return Q, R


In [221]:
def is_converged(R, epsilon):
    rows, cols = R.shape
    sum = 0
    for i in range(1, rows):  # Start from row 1 (skip diagonal)
        for j in range(i):  # Only check lower triangle
            sum += abs(R[i, j])
    return sum

In [228]:
def qr_algorithm_with_shifts(A, refeig=-1, sindex=-1, max_iterations=1000, epsilon = 1e-8):
    # Compute the initial QR decomposition of A
    
    Ai = A
    Q_total = np.eye(A.shape[0])
    
    
    for i in range(max_iterations):
        shift = Ai[refeig, sindex]
        B = Ai
        for j in range(B.shape[0]): # Subtract the shift from the diagonal
            B[j,j] -= shift
        
        Q, R = np.linalg.qr(B)
 
        Ai = R @ Q
        for j in range(Ai.shape[0]): # Add the shift back to the diagonal
            Ai[j,j] += shift

        # Compute the total Q matrix (Q1 * Q2 * ... * Qi)
        Q_total =  Q_total @ Q

        convergence = is_converged(R, epsilon)
        print(f"Iteration: {i} The dconvergence rate is: {diff}")
        
        if (convergence < epsilon):
            print(f"The matrix R is converged: \n{R}")
            break
        
    #Return the diagnol of the matrix as eigen values and the total Q matrix as eigen vectors
    return Ai.diagonal(), Q_total 



In [202]:
def qr_algorithm_recursive(A, max_iterations=1000, epsilon = 1e-8, iterations = 0):
    # Compute the initial QR decomposition of A
    if (iterations >= max_iterations):
        throw("Max iterations reached")
    
    Q, R = np.linalg.qr(A)
    Aj = A # Save the previous iteration matrix
    Ai = R @ Q
    diff = norm(Aj.diagonal() - Ai.diagonal())
    print(f"Iteration: {iterations} The diff is: {diff}")
    
    if (is_converged(Ai, epsilon) and diff < epsilon):
        return Ai.diagonal(), Ai
    else:
        diag, Qt = qr_algorithm_recursive(Ai, max_iterations, epsilon, iterations+1)
    return diag, Qt @ Q

In [203]:
# def is_converged(A, epsilon):
#     """Check if the lower triangular part of A is close to zero."""
#     return np.all(np.abs(np.tril(A, k=-1)) < epsilon)

# def qr_algorithm_recursive(A, max_iterations=1000, epsilon=1e-8, iterations=0, Q_accum=None):
#     if iterations >= max_iterations:
#         raise Exception("Max iterations reached")

#     Q, R = np.linalg.qr(A)  # Compute QR decomposition

#     if Q_accum is None:
#         Q_accum = Q  # Initialize Q accumulation
#     else:
#         Q_accum = Q_accum @ Q  # Accumulate Q for eigenvectors

#     Ai = R @ Q  # Compute next matrix
#     diff = norm(A.diagonal() - Ai.diagonal())

#     #print(f"Iteration {iterations}: diff = {diff}")

#     if is_converged(Ai, epsilon) and diff < epsilon:
#         return Ai.diagonal(), Q_accum  # Eigenvalues and accumulated eigenvectors

#     return qr_algorithm_recursive(Ai, max_iterations, epsilon, iterations+1, Q_accum)

In [229]:
matrix = np.array([[3,0,1],
                   [0,2,2],
                   [1,2,2]])

In [230]:
# Measure time for qr_shifts
start_time = time.time()
eigs_qr, eigv_qr = qr_algorithm_with_shifts(matrix, max_iterations=MAX_ITERATIONS, epsilon = EPSILON)
qr_time = time.time() - start_time
print(f"\nExecution time for qr_shifts: {qr_time:.6f} seconds")

# Measure time for NumPy's eig function
start_time = time.time()
eigs_np, eigv_np = np.linalg.eig(matrix)
np_time = time.time() - start_time
print(f"Execution time for np.linalg.eig: {np_time:.6f} seconds")

Iteration: 0 The diff is: 3.5355339059327373
Iteration: 1 The diff is: 3.577191118223388
Iteration: 2 The diff is: 4.259803273592264
Iteration: 3 The diff is: 5.065964619517175
Iteration: 4 The diff is: 5.1224917161333945
Iteration: 5 The diff is: 4.9173118787266334
Iteration: 6 The diff is: 4.82104167034407
Iteration: 7 The diff is: 4.804774566013441
Iteration: 8 The diff is: 4.802942469548553
Iteration: 9 The diff is: 4.8027626562768155
Iteration: 10 The diff is: 4.802745755744673
Iteration: 11 The diff is: 4.802744188233126
Iteration: 12 The diff is: 4.8027440434346955
Iteration: 13 The diff is: 4.802744030075424
Iteration: 14 The diff is: 4.802744028843341
Iteration: 15 The diff is: 4.802744028729723
Iteration: 16 The diff is: 4.802744028719246
Iteration: 17 The diff is: 4.80274402871828
Iteration: 18 The diff is: 4.802744028718192
Iteration: 19 The diff is: 4.802744028718183
Iteration: 20 The diff is: 4.802744028718182
Iteration: 21 The diff is: 4.802744028718183
Iteration: 22 The

In [231]:
print(f"\nEigenvalues from qr_shifts:\n{eigs_qr}")
print(f"Eigenvalues from np.linalg.eig:\n{eigs_np}")
print(f"\nEigenvectors from qr_shifts:\n{eigv_qr}")
print(f"Eigenvectors from np.linalg.eig:\n{eigv_np}")

print(f"\nEigenvectors difference: {np.linalg.norm(eigv_qr) - np.linalg.norm(eigv_np)}")



Eigenvalues from qr_shifts:
[-0.16424794  4.39138238  2.77286556]
Eigenvalues from np.linalg.eig:
[-2.16424794  0.77286556  2.39138238]

Eigenvectors from qr_shifts:
[[ 0.2260912  -0.48280128  0.84604119]
 [ 0.6611152  -0.56181831 -0.49727948]
 [-0.7154086  -0.6717612  -0.19216509]]
Eigenvectors from np.linalg.eig:
[[ 0.2260912  -0.84604119 -0.48280128]
 [ 0.6611152   0.49727948 -0.56181831]
 [-0.7154086   0.19216509 -0.6717612 ]]

Eigenvectors difference: 4.440892098500626e-16


In [232]:
es = np.array(eigs_qr)
ev = np.array(eigv_qr)
print(matrix @ ev - ev * es)
print()
print(matrix @ eigv_np - eigv_np * eigs_np)

[[-0.45218239  0.96560257 -1.69208238]
 [-1.32223039  1.12363661  0.99455897]
 [ 1.4308172   1.3435224   0.38433019]]

[[-2.77555756e-16  0.00000000e+00 -2.22044605e-16]
 [-4.44089210e-16  1.66533454e-16  2.22044605e-16]
 [-6.66133815e-16  5.55111512e-17 -2.22044605e-16]]
